title: Red Hat Nordics SA Demo lab
description: >- # this means to ignore newlines until "baseurl:"
  We Red Hat Solution Architects share content here which we
  have used to create our own demo labs. Some of it is seen useful starting
  points to our customers too. Ansible, Tower, CloudForms, Satellite, RHV, IdM, RHEL, Gluster, Ceph
show_downloads: false
google_analytics: UA-133655123-1
theme: jekyll-theme-hacker

permalink: "/:title"

plugins:
  - jekyll-paginate

paginate: 10
paginate_path: "/blogs/:num"
